add createpet and deletepet tests
soulmate-git/petstore_autotests pull request #1
Opened 2024-11-14 15:56 UTC by soulmate-git

Создал структуру проекта, написал тесты на добавление и удаление питомца

2024-11-15 12:21 UTC, sh3p42d reviewed
В целом неплохо сделано, все ошибки мелкие и не требуют много времени на исправление.

На подумать: нужен ли тебе в будущем абстрактный BaseTest, от которого наследуются все тесты и в котором лежат все сервисы, контроллеры и общие тестовые методы (создание сущностей, проверки etc.)?

2024-11-15 12:21 UTC, sh3p42d commented on src/main/java/petStore/Main.java
Этот файл тут не нужен

2024-11-15 12:21 UTC, sh3p42d commented on src/main/java/petStore/dto/CreatePetDto.java
> +public class CreatePetDto {
Название класса должно быть существительным, достаточно просто Pet или PetDto

2024-11-15 12:21 UTC, sh3p42d commented on src/main/java/petStore/dto/CreatePetDto.java
> +    public BigDecimal id;
В id не нужна плавающая точка, лучше использовать Long

2024-11-15 12:21 UTC, sh3p42d commented on src/main/java/petStore/dto/CreatePetDto.java
> +    public ArrayList<Tag> tags;
Тут просто List лучше сделать, а то какой именно там будет (ArrayList, LinkedList и т.д.) решать уже в методах.

2024-11-15 12:21 UTC, sh3p42d commented on src/main/java/petStore/providers/CreatePetProvider.java
> +public class CreatePetProvider {
Соответственно здесь просто PetProvider

2024-11-15 12:21 UTC, sh3p42d commented on src/main/java/petStore/services/PetServices.java
> +public class PetServices extends HttpUtil {
PetService, без 's'. И это скорее контроллер, а не сервис

2024-11-15 12:21 UTC, sh3p42d commented on src/main/java/petStore/utils/HttpUtil.java
> +public class HttpUtil {
Вряд ли это можно назвать классом утилит, это скорее базовый класс сервисов (контроллеров). Перенеси в нужный пакет, переименуй в BaseService (BaseController) и сделай абстрактным.

2024-11-15 12:21 UTC, sh3p42d commented on src/main/java/petStore/utils/HttpUtil.java
> +public class HttpUtil {
Из всего класса используется всего два метода, остальные можно убрать. Добавляй их по мере необходимости и тебе не придется поддерживать работоспособность неиспользуемого кода.

2024-11-15 12:21 UTC, sh3p42d commented on src/test/java/petstoretests/CreatePetTest.java
> +        PetServices petService = new PetServices();
В DeletePetTest ты вынес инициализацию куда нужно, а тут забыл?)

2024-11-15 12:21 UTC, sh3p42d commented on src/test/java/petstoretests/CreatePetTest.java
> +        var response = petService.createPet(CreatePetProvider.createPet("Rinna", "available"));
Зачем var? Response response вполне хорошо смотрится. И, пожалуйста, вынеси инициализацию объекта из метода petService.createPet(pet)

2024-11-15 12:21 UTC, sh3p42d commented on src/test/java/petstoretests/CreatePetTest.java
> +        var pet = response.then().extract().as(CreatePetDto.class);
А здесь вместо var поставь PetDto

2024-11-15 12:21 UTC, sh3p42d commented on src/test/java/petstoretests/CreatePetTest.java
> +    public void createPetPositive() {
Раздели, пожалуйста, код на блоки с помощью переносов, например:
Предусловие
Отправка запроса
Проверка

2024-11-15 12:21 UTC, sh3p42d commented on src/main/java/petStore/services/PetServices.java
> +    public Response createPet(CreatePetDto pet) {
Можно не писать Pet, и так понятно будет "PetService.create(pet)"

2024-11-15 12:21 UTC, sh3p42d commented on src/main/java/petStore/services/PetServices.java
> +    public Response deletePet(String id) {
Аналогично с create

2024-11-15 12:21 UTC, sh3p42d commented on src/test/java/petstoretests/CreatePetTest.java
> +        assertEquals("Rinna", pet.getName());
По-хорошему тебе нужно за раз проверить весь ответ, т.к. может возникнуть ситуация, когда у тебя неправильные имя и пустой ID, но про пустой ID ты узнаешь только после исправлений. Подумай как можно проверить всё и сразу

2024-11-15 12:21 UTC, sh3p42d commented on src/test/java/petstoretests/CreatePetTest.java
> +    public void createPetNegative() {
Тест не прошёл у меня

2024-11-15 12:21 UTC, sh3p42d commented on src/test/java/petstoretests/CreatePetTest.java
> +        petService.createPet(CreatePetProvider.createPet(null, null)).then().statusCode(405);
Вынеси, пожалуйста, проверку в assert

2024-11-15 12:21 UTC, sh3p42d commented on src/test/java/petstoretests/DeletePetTest.java
> +        var response = petService.createPet(CreatePetProvider.createPet("Rinna", "available"));
Убрать var, вынести создание объекта из метода

2024-11-15 12:21 UTC, sh3p42d commented on src/test/java/petstoretests/DeletePetTest.java
> +        var pet = response.then().extract().as(CreatePetDto.class);
Убрать var

2024-11-15 12:21 UTC, sh3p42d commented on src/test/java/petstoretests/DeletePetTest.java
> +    public void deletePet() {
Предусловие
Отправка запроса
Проверка

2024-11-15 12:21 UTC, sh3p42d commented on src/test/java/petstoretests/DeletePetTest.java
> +        petService.deletePet(String.valueOf(pet.getId())).then().statusCode(200);
Проверка в assert

2024-11-15 12:21 UTC, sh3p42d commented on src/test/java/petstoretests/DeletePetTest.java
> +        petService.deletePet(null).then().statusCode(404);
Проверка в assert

2024-11-15 12:21 UTC, sh3p42d commented on src/test/java/petstoretests/DeletePetTest.java
> +        petService.deletePet("1111111111111111111111111111111111111111111111111111111111");
Проверка в assert

2024-11-15 15:45 UTC, soulmate-git commented on src/test/java/petstoretests/CreatePetTest.java
> +    public void createPetNegative() {
у меня он тоже не проходит, но мне кажется проблема в самом свагере, я даже если пустой body передаю, он мне почему-то 200ОК пишет

2024-11-16 10:23 UTC, sh3p42d requested changes
Ещё немного замечаний

2024-11-16 10:23 UTC, sh3p42d commented on src/test/java/petstoretests/CreatePetTest.java
> +        Response response = petService.create(createPet("Rinna", "available"));
Надо было вот так:
Pet petRinna = PetProvider.createPet("Rinna", "available");
Response response = petService.create(petRinna);

2024-11-16 10:23 UTC, sh3p42d commented on src/test/java/petstoretests/CreatePetTest.java
> +import static petStore.providers.PetProvider.createPet;
Это здесь лишнее, как по мне

2024-11-16 10:23 UTC, sh3p42d commented on src/test/java/petstoretests/CreatePetTest.java
> +        assertEquals(SC_METHOD_NOT_ALLOWED, petService.create(createPet(null, null)).statusCode());
Аналогично, сначала создай `Pet petNull = PetProvider.createPet(null, null)`,  а потом передавай в метод.

2024-11-16 10:23 UTC, sh3p42d commented on src/test/java/petstoretests/CreatePetTest.java
> +        assertEquals(createPet(pet.getId(), "Rinna", "available"), pet);
Технически, в expected у тебя не тот же самый объект, ты создаешь тут новый.
Если сделаешь создание объекта Pet как показано выше, то сможешь передавать petRinna в ассерты.

2024-11-16 10:23 UTC, sh3p42d commented on src/test/java/petstoretests/DeletePetTest.java
> +        Response response = petService.create(PetProvider.createPet("Rinna", "available"));
Сначала создание Pet

2024-11-16 10:23 UTC, sh3p42d commented on src/test/java/petstoretests/DeletePetTest.java
> +        assertEquals(SC_NOT_FOUND, petService.remove(null).statusCode());
Не засовывай в методы другие методы, у нас тут не West Coast Customs)
Сначала получи statusCode, а затем уже делай проверку:
... statusCode = ...;
assertEquals(SC_NOT_FOUND, statusCode)

2024-11-16 10:23 UTC, sh3p42d commented on src/test/java/petstoretests/DeletePetTest.java
> +        assertEquals(SC_BAD_REQUEST, petService.remove("not_valid_value").statusCode());
Аналогично

2024-11-18 11:51 UTC, sh3p42d approved these changes
Все отлично, молодец!

2024-11-18 14:15 UTC, Diinal commented on src/test/java/petstoretests/CreatePetTest.java
> +    public void createPetNegative() {
все верно, баг сервиса

2024-11-18 14:36 UTC, Diinal requested changes
партия комментов

2024-11-18 14:36 UTC, Diinal commented on .gitignore
> +.apt_generated
почисти от лишних игноров, должны остаться лишь те, что действительно используются

2024-11-18 14:36 UTC, Diinal commented on src/test/java/petstoretests/CreatePetTest.java
> +        assertEquals(SC_OK, statusCode);
я бы вынес проверку статус кода в начало
либо надо использовать софт ассерты, чтобы получить все различия сразу

2024-11-18 14:36 UTC, Diinal commented on src/test/java/petstoretests/CreatePetTest.java
> +    public void createPetPositive() {
не хватает проверок по остальным двум статусам

2024-11-18 14:36 UTC, Diinal commented on src/test/java/petstoretests/DeletePetTest.java
> +    public void deleteById() {
аналогично созданию животного - не хватает статусов

2024-11-18 14:36 UTC, Diinal commented on src/test/java/petstoretests/DeletePetTest.java
> +        assertEquals(SC_OK, statusCode);
также было бы неплохо добавить проверку с гет запросом, где ожидаемый статус будет 404

2024-11-18 14:36 UTC, Diinal commented on src/test/java/petstoretests/CreatePetTest.java
> +        Pet pet = response.as(Pet.class);
что произойдет если получим невалидный json в теле?

2024-11-18 18:26 UTC, soulmate-git commented on src/test/java/petstoretests/CreatePetTest.java
> +    public void createPetPositive() {
в свагере всего 2 статуса, 200 и 405, но 405 не получается получить (видимо баг свагера), даже при пустом body или если передать id некорректно, свагер отдает 200ОК, но сам кейс на проверку 405 я написал в createPetNegative

2024-11-18 18:27 UTC, soulmate-git commented on src/test/java/petstoretests/DeletePetTest.java
> +    public void deleteById() {
Тут так же я расписал кейсы на все статусы из свагера, но 400 получить не удается

2024-11-18 18:30 UTC, soulmate-git commented on src/test/java/petstoretests/CreatePetTest.java
> +        Pet pet = response.as(Pet.class);
по логике тест должен упасть, но тут сваггер все равно дает 200 ОК

2024-11-24 20:00 UTC, sh3p42d requested changes
Не прошли тесты: createPetNegative, deletePetInvalidIdSupplied и getPetListByInvalidStatus. Пометь их аннотациями/комментами почему так происходит.
И не забывай про смысловое разделение кода!

2024-11-24 20:00 UTC, sh3p42d commented on src/main/java/petStore/services/BaseService.java
> +
Лишний перенос

2024-11-24 20:00 UTC, sh3p42d commented on src/test/java/petstoretests/DeletePetTest.java
> +        Long petId = 123L;
Раздели на блоки

2024-11-24 20:00 UTC, sh3p42d commented on src/test/java/petstoretests/GetPetTest.java
> +    public void getPetListByStatus(String status) {
Раздели на блоки

2024-11-24 20:00 UTC, sh3p42d commented on src/test/java/petstoretests/GetPetTest.java
> +        List<Pet> pets = response.as(new TypeRef<>() {
А если вернется пустой список?
Проверь сначала statusCode, затем, что список не пуст, и только потом уже проверяй содержимое списка

2024-11-24 20:00 UTC, sh3p42d commented on src/test/java/petstoretests/GetPetTest.java
> +        for (Pet pet : pets) {
Попробуй переделать на stream

2024-11-24 20:00 UTC, sh3p42d commented on src/test/java/petstoretests/GetPetTest.java
> +
Лишний перенос

2024-11-24 20:00 UTC, sh3p42d commented on src/test/java/petstoretests/UpdatePetTest.java
> +    public void updatePet() {
1. Раздели на блоки
2. Слишком много объектов Pet, нужно сокращать:
создаешь первый oldPet, отправляешь на сервер, достаешь его id (без создания объекта)
создаешь второй newPet, подставляешь id и отправляешь
затем проверяешь oldPet != currentPet и newPet == currentPet (currentPet это тот что на сервере)

2024-11-24 20:00 UTC, sh3p42d commented on src/test/java/petstoretests/UpdatePetTest.java
> +        assertEquals(expectedPet, actualPet);
Не хватает ещё одной проверки, описал выше

2024-11-24 20:00 UTC, sh3p42d commented on src/test/java/petstoretests/DeletePetTest.java
> +        assertEquals(SC_OK, statusCodeCreate);
21 и 22 строки стоит поменять местами

2024-11-27 16:11 UTC, Diinal commented on src/test/java/petstoretests/CreatePetTest.java
> +    public void createPetPositive() {
я про статусы животных писал (available, pending, sold)

2024-12-09 11:04 UTC, sh3p42d requested changes
Несколько минорных замечаний

2024-12-09 11:04 UTC, sh3p42d commented on src/test/java/petstoretests/GetPetTest.java
>          });
Не заметил, убери перенос тут, список пустой же:
List<Pet> pets = response.as(new TypeRef<>() {});

2024-12-09 11:04 UTC, sh3p42d commented on src/test/java/petstoretests/GetPetTest.java
>          assertEquals(SC_OK, statusCode);
Сначала проверяешь статус ответа, а потом тело ответа, писал в прошлый раз

2024-12-09 11:04 UTC, sh3p42d commented on src/test/java/petstoretests/DeletePetTest.java
> +        Long petId = 123L;
Не разделил

2024-12-09 11:04 UTC, sh3p42d commented on src/test/java/petstoretests/UpdatePetTest.java
> +        Pet oldPet = petService.create(createPet("Tom", "available")).as(Pet.class);
1. Сначала создай Pet, а потом его отправляй. Не надо создавать объекты в методах
2. Не хватает проверки, если petService.create вернет statusCode не ОК

2024-12-09 11:04 UTC, sh3p42d commented on src/test/java/petstoretests/UpdatePetTest.java
>          assertEquals(SC_OK,statusCode);
Проверка статуса должна быть первой

2024-12-23 03:45 UTC, sh3p42d approved these changes
Замечания исправлены

2024-12-24 07:28 UTC, sh3p42d requested changes
Нужны небольшие правки

2024-12-24 07:28 UTC, sh3p42d commented on src/main/java/petStore/services/PetService.java
> +    public  Response create(Pet pet) {
Зачем пробел?)

2024-12-24 07:28 UTC, sh3p42d commented on src/test/java/petstoretests/CreateOrderTest.java
> +        Response responseCreateOrder = storeService.createOrder(newOrder);
Ну вот опять же, где здесь предусловие, а где действие, которое проверяешь? Раздели логическим переносом

2024-12-24 07:28 UTC, sh3p42d commented on src/test/java/petstoretests/DeleteOrderTest.java
> +        Order order = responseCreateOrder.as(Order.class);
Перенос?

2024-12-24 07:28 UTC, sh3p42d commented on src/test/java/petstoretests/CreateOrderTest.java
> +        Order newOrder = OrderProvider.createOrder(null, null, true);
Возможно нужен перенос?

2024-12-27 03:23 UTC, sh3p42d approved these changes

2024-12-27 11:08 UTC, Diinal approved these changes

2025-02-24 06:47 UTC, merged